apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 5000
      nodePort: 30002
  selector:
    app: app-api
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5001
      nodePort: 30001
  selector:
    app: auth-api